### PR TITLE
Adds support for laravel 5.8

### PR DESCRIPTION
**Pull request by elbojoloco**

### CODE REVIEW

**Comment by rickselby** [comment]
Can you add a test to .travis.yml too, please?

**Comment by elbojoloco** [comment]
I don't know why it's failing, maybe you can look at it?

**Comment by rickselby** [comment]
I think the ``setUp(): void`` needs to be done in all three test files?

**Comment by elbojoloco** [comment]
I added the `setUp(): void` compatibility for all tests, let's see.

**Comment by elbojoloco** [comment]
I think drop php 7.0 support?

**Comment by rickselby** [comment]
Yeah that's fine, it's EOL anyway.

**Comment by rickselby** [comment]
Thank you!

**Pull request merged**
